version: "3"
services:
  papershare_frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    tty: true
    volumes:
      - ../frontend:/src/frontend #マウントするフォルダ
    environment: #環境変数
      SHELL: "/bin/bash"
    ports:
      - "8080:8080"
    working_dir: /src/frontend
    command: bash -c "npm install && npm start"

  papershare_backend:
    build:
      context: .
      dockerfile: Dockerfile_back
    tty: true
    volumes:
      - ../backend:/src/backend #マウントするフォルダ
    environment: #環境変数
      SHELL: "/bin/bash"
    ports:
      - "8000:8000"
    working_dir: /src/backend
    command: bash -c "pip install -r requirements.txt && python manage.py runserver 0.0.0.0:8000"